import Head from 'next/head'
import '../styles/globals.css'
import { Provider } from 'react-redux';
import store from '../store';

function MyApp({ Component, pageProps }) {
  return (
  <Provider store={store}>
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Component {...pageProps} />
  </Provider>
  )
}

export default MyApp
